CREATE TABLE IF NOT EXISTS "PREFERENCIAS" (
	"PREFERENCIAS_ID"	INTEGER NOT NULL UNIQUE,
	"NOMBRE"	TEXT NOT NULL,
	"TEMA"	TEXT,
	PRIMARY KEY("PREFERENCIAS_ID" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "FANHUNTER" (
	"FANHUNTER_ID"	INTEGER NOT NULL UNIQUE,
	"FICHA_ID"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("FANHUNTER_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "FICHAS_FANHUNTER" (
	"FICHAS_ID"	INTEGER NOT NULL UNIQUE,
	"NOMBRE"	INTEGER NOT NULL,
	"ARQUETIPO"	INTEGER,
	"REGLA_ESPECIAL"	INTEGER,
	"TRANSFONDO"	INTEGER,
	"PARADA"	INTEGER,
	"PEEQUIS"	INTEGER,
	"POTRA_TOTAL"	INTEGER,
	"POTRA_ACTUAL"	INTEGER,
	"PUPAS_TOTAL"	INTEGER,
	"PUPAS_ACTUAL"	INTEGER,
	"ATRIBUTOS"	INTEGER,
  "HABILIDADES" INTEGER,
	"ARMAS"	INTEGER,
	"SUPERPODERES"	INTEGER,
	"CONAS"	INTEGER,
	"TARAS"	INTEGER,
	"PANOJA"	INTEGER,
	"EQUIPO"	INTEGER,
	"OTROS"	INTEGER,
	PRIMARY KEY("FICHAS_ID" AUTOINCREMENT)
);

CREATE UNIQUE INDEX IF NOT EXISTS "FICHAS_FANHUNTER_ID" ON "FICHAS_FANHUNTER"("FICHAS_ID");

CREATE TABLE IF NOT EXISTS "ARQUETIOS" (
	"ARQUETIPOS_ID"	INTEGER NOT NULL UNIQUE,
	"NOMBRE"	TEXT,
  "DESCRIPCION" TEXT,
	"HABILIDADES"	TEXT,
	"PUNTOS"	INTEGER,
  "PUNTOS_OBLIGATORIOS" INTEGER,
	"HABILIDAD_ESPECIAL"	INTEGER,
	PRIMARY KEY("ARQUETIPOS_ID" AUTOINCREMENT)
  FOREIGN KEY("HABILIDAD_ESPECIAL") REFERENCES "HABILIDADES_ESPECIALES"("HABILIDADES_ESPECIALES_ID")
);

CREATE TABLE IF NOT EXISTS "HABILIDADES_ESPECIALES" (
  "HABILIDADES_ESPECIALES_ID" INTEGER NOT NULL UNIQUE,
  "NOMBRE" TEXT,
  "HABILIDAD" TEXT,
  "CONA_ASOCIADA" INTEGER,
  PRIMARY KEY("HABILIDADES_ESPECIALES_ID" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "FICHA_ARQUETIPO" (
  "FICHA_ARQUETIPO_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
  "ARQUETIPO" INTEGER,
  PRIMARY KEY("FICHA_ARQUETIPO_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "NOMBRES" (
	"NOMBRES_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
	"NOMBRE" TEXT,
	PRIMARY KEY("NOMBRES_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
	);

CREATE TABLE IF NOT EXISTS "FICHA_ATRIBUTOS" (
  "FICHA_ATRIBUTOS_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
	"HOSTIAS" INTEGER,
	"TIROS" INTEGER,
	"MUSCULOS" INTEGER,
	"REFLEJOS" INTEGER,
	"NEURONAS" INTEGER,
	"PERCEPCION" INTEGER,
	"AGALLAS" INTEGER,
	"CARISMA" INTEGER,
	PRIMARY KEY("FICHA_ATRIBUTOS_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "FICHA_HABILIDADES" (
  "FICHA_HABILIDADES_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
	"DEFENSA" INTEGER,
	"TACTICA" INTEGER,
	"ARTILLERIA" INTEGER,
	"LANZAR" INTEGER,
	"ATLETISMO" INTEGER,
	"INTIMIDAR" INTEGER,
	"CABRIOLAS" INTEGER,
	"MANITAS" INTEGER,
	"INVESTIGAR" INTEGER,
	"MATASANOS" INTEGER,
	"ALERTA" INTEGER,
	"CHANCHULLOS" INTEGER,
	"SIGILO" INTEGER,
	"EXPLOSIVOS" INTEGER,
	"COMECOCOS" INTEGER,
	"FAROLEAR" INTEGER,
	PRIMARY KEY("FICHA_HABILIDADES_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "FICHA_MAESTRIA" (
  "FICHA_MAESTRIA_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
  "MAESTRIA" TEXT,
  "VALOR" INTEGER,
  PRIMARY KEY("FICHA_MAESTRIA_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "FICHA_PRECISION" (
  "FICHA_PRECISION_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
  "PRECISION" TEXT,
  "VALOR" INTEGER,
  PRIMARY KEY("FICHA_PRECISION_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "FICHA_SUPERVIVENCIA" (
  "FICHA_SUPERVIVENCIA_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
  "SUPERVIVENCIA" TEXT,
  "VALOR" INTEGER,
  PRIMARY KEY("FICHA_SUPERVIVENCIA_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "FICHA_VEHICULO" (
  "FICHA_VEHICULO_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
  "VEHICULO" TEXT,
  "VALOR" INTEGER,
  PRIMARY KEY("FICHA_VEHICULO_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "FICHA_CULTURILLA" (
  "FICHA_CULTURILLA_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
  "CULTURILLA" TEXT,
  "VALOR" INTEGER,
  PRIMARY KEY("FICHA_CULTURILLA_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "FICHA_IDIOMA" (
  "FICHA_IDIOMA_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
  "IDIOMA" TEXT,
  "VALOR" INTEGER,
  PRIMARY KEY("FICHA_IDIOMA_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "FICHA_CRIMEN" (
  "FICHA_CRIME_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
  "CRIMEN" TEXT,
  "VALOR" INTEGER,
  PRIMARY KEY("FICHA_CRIME_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "FICHA_TALENTO" (
  "FICHA_TALENTO_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
  "TALENTO" TEXT,
  "VALOR" INTEGER,
  PRIMARY KEY("FICHA_TALENTO_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "FICHA_ARMAS" (
  "FICHA_ARMAS_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
  "ARMA" INTEGER,
  PRIMARY KEY("FICHA_ARMAS_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "FICHA_SUPER_PODERES" (
  "FICHA_SUPER_PODER_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
  "SUPERPODER" INTEGER,
  PRIMARY KEY("FICHA_SUPER_PODER_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "FICHA_CONAS" (
  "FICHA_CONAS_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
  "CONA" INTEGER,
  PRIMARY KEY("FICHA_CONAS_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "FICHA_TARAS" (
  "FICHA_TARAS_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
  "TARA" INTEGER,
  PRIMARY KEY("FICHA_TARAS_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "FICHA_PANOJA" (
  "FICHA_PANOJA_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
  "PANOJA" INTEGER,
  PRIMARY KEY("FICHA_PANOJA_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "FICHA_EQUIPOS" (
  "FICHA_EQUIPOS_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
  "EQUIPO" INTEGER,
  PRIMARY KEY("FICHA_EQUIPOS_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "FICHA_NOTAS" (
  "FICHA_NOTAS_ID" INTEGER NOT NULL UNIQUE,
  "FICHA_ID" INTEGER NOT NULL,
  "NOTAS" INTEGER,
  PRIMARY KEY("FICHA_NOTAS_ID" AUTOINCREMENT)
  FOREIGN KEY("FICHA_ID") REFERENCES "FICHAS_FANHUNTER"("FICHAS_ID")
);

CREATE TABLE IF NOT EXISTS "ARMAS" (
  "ARMA_ID" INTEGER NOT NULL,
  "NOMBRE" text,
  "ALCANCE" INTEGER,
  "CARGADOR" INTEGER,
  "MANOS" INTEGER,
  "RAFAGA" INTEGER,
  "DANO" INTEGER,
  "ARMAS_REGLAS_ESPECIALES" INTEGER,
  PRIMARY KEY("ARMA_ID" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "ARMAS_REGLAS_ESPECIALES" (
  "ARMAS_REGLAS_ESPECIALES_ID" INTEGER NOT NULL UNIQUE,
  "NOBRE" TEXT,
  "REGLA" TEXT,
  PRIMARY KEY("ARMAS_REGLAS_ESPECIALES_ID" AUTOINCREMENT)
);